name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: SonarCloud Scan
            uses: hakimio/sonarcloud-github-action@pr-fix
            env:
              GITHUB_TOKEN: ${{ secrets.DEVELOPER_TOKEN }}
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Deploy to GH Pages
        run: |
          git config --global user.email "ottercoder@gmail.com"
          git config --global user.name "ottercoder"
          git remote set-url origin https://${{ secrets.DEVELOPER_TOKEN }}@github.com/ottercoder/new-react-website.git
          npm run deploy